name: Anthony
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Anthony
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1e1c'
    - '#ff7c6a'
    - '#633b34'
    - '#000000'
    - '#111111'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
