name: anthonyklein
favicon: null
layout_spectrum: 0.5877895657904446
typography_spectrum: 0.8094453210942447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2384031186811626
  lightness: 0.3594504336360842
  saturation: 0.697299180785194
  rhythmicContrast: 0.3483352898620069
purpose: []
